"""create ai mentor tables

Revision ID: 8d4063b0ab9f
Revises: 9ed5260c4037
Create Date: 2026-07-22 06:48:49.248938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4063b0ab9f'
down_revision: Union[str, Sequence[str], None] = '9ed5260c4037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_mentor_diagnostic_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('answer_type', sa.String(length=30), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("answer_type IN ('single_choice', 'multiple_choice', 'short_text', 'long_text', 'number', 'boolean')", name='ck_ai_diag_question_answer_type'),
    sa.CheckConstraint('sort_order >= 0', name='ck_ai_diag_question_sort'),
    sa.CheckConstraint('version >= 1', name='ck_ai_diag_question_version'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_code', 'version', name='uq_ai_diag_question_code_version')
    )
    op.create_index(op.f('ix_ai_mentor_diagnostic_questions_category'), 'ai_mentor_diagnostic_questions', ['category'], unique=False)
    op.create_index(op.f('ix_ai_mentor_diagnostic_questions_id'), 'ai_mentor_diagnostic_questions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_diagnostic_questions_question_code'), 'ai_mentor_diagnostic_questions', ['question_code'], unique=False)
    op.create_table('ai_mentor_diagnostic_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'cancelled')", name='ck_ai_diag_session_status'),
    sa.CheckConstraint('version >= 1', name='ck_ai_diag_session_version'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'version', name='uq_ai_diag_session_student_version')
    )
    op.create_index(op.f('ix_ai_mentor_diagnostic_sessions_id'), 'ai_mentor_diagnostic_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_diagnostic_sessions_status'), 'ai_mentor_diagnostic_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_mentor_diagnostic_sessions_student_id'), 'ai_mentor_diagnostic_sessions', ['student_id'], unique=False)
    op.create_table('ai_mentor_diagnostic_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['ai_mentor_diagnostic_questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_mentor_diagnostic_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_ai_diag_answer_session_question')
    )
    op.create_index(op.f('ix_ai_mentor_diagnostic_answers_id'), 'ai_mentor_diagnostic_answers', ['id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_diagnostic_answers_question_id'), 'ai_mentor_diagnostic_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_diagnostic_answers_session_id'), 'ai_mentor_diagnostic_answers', ['session_id'], unique=False)
    op.create_table('ai_mentor_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_session_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('generation_source', sa.String(length=30), nullable=False),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("generation_source IN ('mock', 'llm', 'manual')", name='ck_ai_plan_generation_source'),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'archived')", name='ck_ai_plan_status'),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_ai_plan_date_range'),
    sa.CheckConstraint('version >= 1', name='ck_ai_plan_version'),
    sa.ForeignKeyConstraint(['diagnostic_session_id'], ['ai_mentor_diagnostic_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'version', name='uq_ai_plan_student_version')
    )
    op.create_index(op.f('ix_ai_mentor_plans_diagnostic_session_id'), 'ai_mentor_plans', ['diagnostic_session_id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_plans_id'), 'ai_mentor_plans', ['id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_plans_status'), 'ai_mentor_plans', ['status'], unique=False)
    op.create_index(op.f('ix_ai_mentor_plans_student_id'), 'ai_mentor_plans', ['student_id'], unique=False)
    op.create_table('ai_mentor_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'closed', 'archived')", name='ck_ai_chat_session_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['ai_mentor_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_mentor_chat_sessions_id'), 'ai_mentor_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_chat_sessions_plan_id'), 'ai_mentor_chat_sessions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_chat_sessions_status'), 'ai_mentor_chat_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_mentor_chat_sessions_student_id'), 'ai_mentor_chat_sessions', ['student_id'], unique=False)
    op.create_table('ai_mentor_plan_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('week_number BETWEEN 1 AND 4', name='ck_ai_plan_week_number'),
    sa.ForeignKeyConstraint(['plan_id'], ['ai_mentor_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'week_number', name='uq_ai_plan_week_plan_number')
    )
    op.create_index(op.f('ix_ai_mentor_plan_weeks_id'), 'ai_mentor_plan_weeks', ['id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_plan_weeks_plan_id'), 'ai_mentor_plan_weeks', ['plan_id'], unique=False)
    op.create_table('ai_mentor_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('system', 'user', 'assistant')", name='ck_ai_chat_message_role'),
    sa.CheckConstraint('sequence_number >= 1', name='ck_ai_chat_message_sequence'),
    sa.CheckConstraint('token_count IS NULL OR token_count >= 0', name='ck_ai_chat_message_tokens'),
    sa.ForeignKeyConstraint(['session_id'], ['ai_mentor_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence_number', name='uq_ai_chat_message_session_sequence')
    )
    op.create_index(op.f('ix_ai_mentor_chat_messages_created_at'), 'ai_mentor_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_mentor_chat_messages_id'), 'ai_mentor_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_chat_messages_role'), 'ai_mentor_chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_ai_mentor_chat_messages_session_id'), 'ai_mentor_chat_messages', ['session_id'], unique=False)
    op.create_table('ai_mentor_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_week_id', sa.Integer(), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('resources_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'skipped')", name='ck_ai_plan_item_status'),
    sa.CheckConstraint('day_number IS NULL OR day_number BETWEEN 1 AND 7', name='ck_ai_plan_item_day'),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes > 0', name='ck_ai_plan_item_duration'),
    sa.CheckConstraint('item_order >= 1', name='ck_ai_plan_item_order'),
    sa.ForeignKeyConstraint(['plan_week_id'], ['ai_mentor_plan_weeks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_week_id', 'item_order', name='uq_ai_plan_item_week_order')
    )
    op.create_index(op.f('ix_ai_mentor_plan_items_activity_type'), 'ai_mentor_plan_items', ['activity_type'], unique=False)
    op.create_index(op.f('ix_ai_mentor_plan_items_id'), 'ai_mentor_plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_plan_items_plan_week_id'), 'ai_mentor_plan_items', ['plan_week_id'], unique=False)
    op.create_index(op.f('ix_ai_mentor_plan_items_status'), 'ai_mentor_plan_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_mentor_plan_items_status'), table_name='ai_mentor_plan_items')
    op.drop_index(op.f('ix_ai_mentor_plan_items_plan_week_id'), table_name='ai_mentor_plan_items')
    op.drop_index(op.f('ix_ai_mentor_plan_items_id'), table_name='ai_mentor_plan_items')
    op.drop_index(op.f('ix_ai_mentor_plan_items_activity_type'), table_name='ai_mentor_plan_items')
    op.drop_table('ai_mentor_plan_items')
    op.drop_index(op.f('ix_ai_mentor_chat_messages_session_id'), table_name='ai_mentor_chat_messages')
    op.drop_index(op.f('ix_ai_mentor_chat_messages_role'), table_name='ai_mentor_chat_messages')
    op.drop_index(op.f('ix_ai_mentor_chat_messages_id'), table_name='ai_mentor_chat_messages')
    op.drop_index(op.f('ix_ai_mentor_chat_messages_created_at'), table_name='ai_mentor_chat_messages')
    op.drop_table('ai_mentor_chat_messages')
    op.drop_index(op.f('ix_ai_mentor_plan_weeks_plan_id'), table_name='ai_mentor_plan_weeks')
    op.drop_index(op.f('ix_ai_mentor_plan_weeks_id'), table_name='ai_mentor_plan_weeks')
    op.drop_table('ai_mentor_plan_weeks')
    op.drop_index(op.f('ix_ai_mentor_chat_sessions_student_id'), table_name='ai_mentor_chat_sessions')
    op.drop_index(op.f('ix_ai_mentor_chat_sessions_status'), table_name='ai_mentor_chat_sessions')
    op.drop_index(op.f('ix_ai_mentor_chat_sessions_plan_id'), table_name='ai_mentor_chat_sessions')
    op.drop_index(op.f('ix_ai_mentor_chat_sessions_id'), table_name='ai_mentor_chat_sessions')
    op.drop_table('ai_mentor_chat_sessions')
    op.drop_index(op.f('ix_ai_mentor_plans_student_id'), table_name='ai_mentor_plans')
    op.drop_index(op.f('ix_ai_mentor_plans_status'), table_name='ai_mentor_plans')
    op.drop_index(op.f('ix_ai_mentor_plans_id'), table_name='ai_mentor_plans')
    op.drop_index(op.f('ix_ai_mentor_plans_diagnostic_session_id'), table_name='ai_mentor_plans')
    op.drop_table('ai_mentor_plans')
    op.drop_index(op.f('ix_ai_mentor_diagnostic_answers_session_id'), table_name='ai_mentor_diagnostic_answers')
    op.drop_index(op.f('ix_ai_mentor_diagnostic_answers_question_id'), table_name='ai_mentor_diagnostic_answers')
    op.drop_index(op.f('ix_ai_mentor_diagnostic_answers_id'), table_name='ai_mentor_diagnostic_answers')
    op.drop_table('ai_mentor_diagnostic_answers')
    op.drop_index(op.f('ix_ai_mentor_diagnostic_sessions_student_id'), table_name='ai_mentor_diagnostic_sessions')
    op.drop_index(op.f('ix_ai_mentor_diagnostic_sessions_status'), table_name='ai_mentor_diagnostic_sessions')
    op.drop_index(op.f('ix_ai_mentor_diagnostic_sessions_id'), table_name='ai_mentor_diagnostic_sessions')
    op.drop_table('ai_mentor_diagnostic_sessions')
    op.drop_index(op.f('ix_ai_mentor_diagnostic_questions_question_code'), table_name='ai_mentor_diagnostic_questions')
    op.drop_index(op.f('ix_ai_mentor_diagnostic_questions_id'), table_name='ai_mentor_diagnostic_questions')
    op.drop_index(op.f('ix_ai_mentor_diagnostic_questions_category'), table_name='ai_mentor_diagnostic_questions')
    op.drop_table('ai_mentor_diagnostic_questions')
    # ### end Alembic commands ###
