"""add analytics fields to students and tasks

Revision ID: 9ed5260c4037
Revises: b12c9b5a1d33
Create Date: 2026-07-15 11:16:11.099760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed5260c4037'
down_revision: Union[str, Sequence[str], None] = 'b12c9b5a1d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('group_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('experiment_group', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('cohort_year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_students_cohort_year'), 'students', ['cohort_year'], unique=False)
    op.create_index(op.f('ix_students_experiment_group'), 'students', ['experiment_group'], unique=False)
    op.create_index(op.f('ix_students_group_name'), 'students', ['group_name'], unique=False)
    op.add_column('tasks', sa.Column('topic', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('week_number', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('assessment_stage', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('academic_period', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tasks_academic_period'), 'tasks', ['academic_period'], unique=False)
    op.create_index(op.f('ix_tasks_assessment_stage'), 'tasks', ['assessment_stage'], unique=False)
    op.create_index(op.f('ix_tasks_topic'), 'tasks', ['topic'], unique=False)
    op.create_index(op.f('ix_tasks_week_number'), 'tasks', ['week_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_week_number'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_topic'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assessment_stage'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_academic_period'), table_name='tasks')
    op.drop_column('tasks', 'academic_period')
    op.drop_column('tasks', 'assessment_stage')
    op.drop_column('tasks', 'week_number')
    op.drop_column('tasks', 'topic')
    op.drop_index(op.f('ix_students_group_name'), table_name='students')
    op.drop_index(op.f('ix_students_experiment_group'), table_name='students')
    op.drop_index(op.f('ix_students_cohort_year'), table_name='students')
    op.drop_column('students', 'cohort_year')
    op.drop_column('students', 'experiment_group')
    op.drop_column('students', 'group_name')
    # ### end Alembic commands ###
